### ISSUE TITLE
Module fails to build in kernel 4.19.10

### ISSUE THREAD

**Issue by thirdwheel** [ppickfor/rr232x-linux#1]
```
# make
fatal: No names found, cannot describe anything.
make[1]: Entering directory '/usr/src/linux-4.19.10'
Makefile:960: "Cannot use CONFIG_STACK_VALIDATION=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel"
  CC [M]  /usr/src/rr232x-linux/product/rr232x/linux/.build/os_linux.o
/usr/src/rr232x-linux/product/rr232x/linux/.build/os_linux.c: In function 'os_request_timer':
/usr/src/rr232x-linux/product/rr232x/linux/.build/os_linux.c:562:27: error: assignment to 'void (*)(struct timer_list *)' from incompatible pointer type 'void (*)(long unsigned int)' [-Werror=incompatible-pointer-types]
  vbus_ext->timer.function = os_timer_for_ldm;
                           ^
/usr/src/rr232x-linux/product/rr232x/linux/.build/os_linux.c:563:17: error: 'struct timer_list' has no member named 'data'
  vbus_ext->timer.data = (unsigned long)vbus_ext;
                 ^
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:304: /usr/src/rr232x-linux/product/rr232x/linux/.build/os_linux.o] Error 1
make[1]: *** [Makefile:1517: _module_/usr/src/rr232x-linux/product/rr232x/linux/.build] Error 2
make[1]: Leaving directory '/usr/src/linux-4.19.10'
make: *** [../../../inc/linux/Makefile.def:107: rr232x.ko] Error 2
```

**Comment by thirdwheel** [comment]
I'll note here that it builds successfully in Linux 4.14.10.

**Comment by thirdwheel** [comment]
Oh, by the way, to reproduce my build environment:

1. Boot Tinycore Linux 10.1 on something with at least 2GB RAM. No need to install.
2. Install compilers, git and the source: `tce-load -wi compiletc git linux-kernel-sources-env`
3. Set up the kernel sources: `linux-kernel-sources-env.sh`
